source 'http://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'geckodriver-helper'
gem 'rest-client'
gem 'site_prism'
gem 'rails'
gem 'cpf_cnpj'
gem 'allure-cucumber'
gem 'webdrivers'
gem 'colorize'